[build]
  functions = "functions"
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
